// Per-year page content (Prep–Year 6), sourced from the MyMathsHero SEO copy.
// Keyed by URL slug. Each entry drives one /curriculum/[slug] page + its SEO.
export const YEAR_CONTENT = {
  prep: {
    slug: 'prep',
    label: 'Prep',
    title: 'Prep Maths Learning for Australian Children | MyMathsHero',
    description: 'Help your child build confidence with Prep maths. MyMathsHero provides personalised, curriculum-aligned maths practice for early counting, numbers, shapes, patterns and problem-solving.',
    heading: 'Prep Maths Learning — Building Strong Foundations from the Start',
    tagline: 'Personalised, curriculum-aligned maths practice for your child\'s very first year of school.',
    paragraphs: [
      'Prep is where your child\'s formal maths journey begins. At this stage, children are learning how to make sense of numbers, patterns, shapes, sizes and everyday problem-solving through simple, visual and engaging activities.',
      'At MyMathsHero, our Prep maths program is designed to help young learners feel confident with maths from the very beginning. Children practise important early numeracy skills such as counting, recognising numbers, comparing objects, identifying shapes, continuing patterns, understanding position, exploring measurement and answering simple maths questions.',
      'Every child starts Prep with different experiences and levels of confidence. That is why MyMathsHero uses personalised AI-powered learning to support each child at their own pace, with questions aligned to Australian curriculum standards across all states and territories.',
      'Prep maths should feel positive, simple and achievable. With MyMathsHero, children can build confidence step by step and create a strong foundation for future maths learning.',
    ],
    skills: ['Counting and recognising numbers', 'Comparing objects and quantities', 'Identifying 2D and 3D shapes', 'Continuing simple patterns', 'Understanding position and direction', 'Exploring early measurement'],
  },
  'year-1': {
    slug: 'year-1',
    label: 'Year 1',
    title: 'Year 1 Maths Learning for Australian Children | MyMathsHero',
    description: 'Support your child with Year 1 maths practice. MyMathsHero provides personalised, curriculum-aligned learning for counting, addition, subtraction, shapes, measurement and problem-solving.',
    heading: 'Year 1 Maths Learning — Helping Children Grow in Confidence',
    tagline: 'Personalised, curriculum-aligned maths practice as your child grows into a more confident thinker.',
    paragraphs: [
      'Year 1 is an important year where children begin to move beyond early number recognition and start developing stronger maths understanding. Students build confidence with counting, number order, addition, subtraction, patterns, shapes, measurement and simple problem-solving.',
      'At MyMathsHero, our Year 1 program helps children practise key skills such as reading and writing numbers, counting forwards and backwards, comparing quantities, solving simple addition and subtraction questions, recognising patterns, exploring 2D and 3D shapes, and using measurement in everyday situations.',
      'Every child learns differently. MyMathsHero uses personalised AI-powered learning to give each child questions that suit their ability, helping them practise without feeling rushed or overwhelmed — all aligned with curriculum standards across every Australian state and territory.',
      'With regular practice and the right support, Year 1 students can build strong number confidence, improve problem-solving skills and develop a positive attitude towards maths.',
    ],
    skills: ['Reading and writing numbers', 'Counting forwards and backwards', 'Simple addition and subtraction', 'Comparing quantities', 'Recognising patterns', 'Exploring 2D and 3D shapes'],
  },
  'year-2': {
    slug: 'year-2',
    label: 'Year 2',
    title: 'Year 2 Maths Learning for Australian Children | MyMathsHero',
    description: 'Build your child\'s confidence with Year 2 maths. MyMathsHero offers personalised, curriculum-aligned practice for place value, addition, subtraction, shapes, measurement, data and problem-solving.',
    heading: 'Year 2 Maths Learning — Strengthening Skills and Number Confidence',
    tagline: 'Personalised, curriculum-aligned practice as children develop fluency and independence.',
    paragraphs: [
      'Year 2 is a key stage where children begin to develop stronger fluency and independence in maths. Students start working with larger numbers, place value, addition, subtraction, simple multiplication, division, patterns, shapes, measurement, time, money, data and problem-solving.',
      'At MyMathsHero, our Year 2 program helps children strengthen their number knowledge, use mental strategies, recognise patterns, compare values, solve everyday maths problems, explore 2D and 3D shapes, measure length and area, read simple data, and build confidence with real-world maths situations.',
      'Year 2 learners often show clear differences in confidence. MyMathsHero uses personalised AI-powered learning to provide questions that match each child\'s level, aligned with curriculum standards across Australian states and territories.',
      'With the right practice, Year 2 students can become more confident, accurate and flexible in the way they use maths, developing strong foundations and good problem-solving habits.',
    ],
    skills: ['Place value with larger numbers', 'Addition and subtraction strategies', 'Simple multiplication and division', 'Measuring length and area', 'Telling time and using money', 'Reading simple data'],
  },
  'year-3': {
    slug: 'year-3',
    label: 'Year 3',
    title: 'Year 3 Maths Learning for Australian Children | MyMathsHero',
    description: 'Support your child with Year 3 maths practice. MyMathsHero provides personalised, curriculum-aligned learning for multiplication, division, fractions, measurement, data and problem-solving.',
    heading: 'Year 3 Maths Learning — Building Confidence for Middle Primary',
    tagline: 'Personalised, curriculum-aligned practice as your child becomes a more independent learner.',
    paragraphs: [
      'Year 3 is an important step in your child\'s maths development, moving from simple number practice into more structured problem-solving, stronger mental strategies and deeper mathematical thinking.',
      'In Year 3, children build understanding of place value, addition, subtraction, multiplication, division, fractions, number patterns, shapes, angles, measurement, time, money, chance, data and worded problems. MyMathsHero helps them practise times tables, division facts, comparing fractions, multi-step questions, reading graphs, measuring length and mass, working with money and understanding simple chance.',
      'As children enter middle primary, gaps in understanding can become more noticeable. MyMathsHero uses personalised AI-powered learning to identify what each child needs and provide questions at the right level, aligned with curriculum standards across Australian states and territories.',
      'With regular practice and clear guidance, Year 3 students can strengthen their maths confidence, improve accuracy and develop better problem-solving habits.',
    ],
    skills: ['Times tables and division facts', 'Comparing fractions', 'Multi-step word problems', 'Reading and making graphs', 'Measuring length and mass', 'Time, money and simple chance'],
  },
  'year-4': {
    slug: 'year-4',
    label: 'Year 4',
    title: 'Year 4 Maths Learning for Australian Children | MyMathsHero',
    description: 'Help your child build confidence with Year 4 maths. MyMathsHero offers personalised, curriculum-aligned practice for multiplication, division, fractions, decimals, measurement and problem-solving.',
    heading: 'Year 4 Maths Learning — Developing Stronger Skills for Upper Primary',
    tagline: 'Personalised, curriculum-aligned practice as children take on more challenging concepts.',
    paragraphs: [
      'Year 4 is a stage where children begin to take on more challenging maths concepts and apply their knowledge with greater independence. Students work more confidently with larger numbers, multiplication, division, fractions, decimals, patterns, measurement, shapes, angles, data and worded problems.',
      'At MyMathsHero, our Year 4 program helps students strengthen the skills they need for upper primary — times tables, division strategies, place value, equivalent fractions, simple decimals, perimeter, area, time, money, symmetry, graphs and multi-step problem-solving.',
      'Year 4 maths often requires students to think carefully about which strategy to use, not just how to calculate. MyMathsHero uses personalised AI-powered learning to provide questions that match each child\'s level, aligned with curriculum standards across Australian states and territories.',
      'With consistent practice and the right guidance, Year 4 students can improve accuracy, strengthen problem-solving skills and build a more positive attitude towards maths.',
    ],
    skills: ['Times tables and division strategies', 'Equivalent fractions and simple decimals', 'Perimeter and area', 'Symmetry and angles', 'Reading and making graphs', 'Multi-step problem-solving'],
  },
  'year-5': {
    slug: 'year-5',
    label: 'Year 5',
    title: 'Year 5 Maths Learning for Australian Children | MyMathsHero',
    description: 'Support your child with Year 5 maths practice. MyMathsHero provides personalised, curriculum-aligned learning for fractions, decimals, percentages, measurement, data and problem-solving.',
    heading: 'Year 5 Maths Learning — Preparing Students for More Advanced Maths',
    tagline: 'Personalised, curriculum-aligned practice as students build accuracy and independence.',
    paragraphs: [
      'Year 5 is an important year where students begin working with more complex maths concepts and are expected to explain their thinking with greater confidence — larger numbers, multiplication, division, fractions, decimals, percentages, patterns, measurement, geometry, chance, data and multi-step problem-solving.',
      'At MyMathsHero, our Year 5 program helps students practise factors and multiples, long multiplication, division strategies, equivalent fractions, adding and comparing fractions, decimal place value, simple percentages, area, perimeter, volume, angles, graphs and worded problems.',
      'Year 5 maths often requires students to connect different ideas and choose the most effective strategy. MyMathsHero uses personalised AI-powered learning to provide questions that match each child\'s level, aligned with curriculum standards across Australian states and territories.',
      'With regular practice and clear guidance, Year 5 students can strengthen problem-solving skills, improve number fluency and feel more prepared for upper-primary assessments and future secondary school maths.',
    ],
    skills: ['Factors, multiples and long multiplication', 'Adding and comparing fractions', 'Decimals and simple percentages', 'Area, perimeter and volume', 'Angles and geometry', 'Interpreting graphs and data'],
  },
  'year-6': {
    slug: 'year-6',
    label: 'Year 6',
    title: 'Year 6 Maths Learning for Australian Children | MyMathsHero',
    description: 'Prepare your child for secondary school with Year 6 maths practice. MyMathsHero offers personalised, curriculum-aligned learning for fractions, decimals, percentages, geometry, data and problem-solving.',
    heading: 'Year 6 Maths Learning — Building Confidence Before Secondary School',
    tagline: 'Personalised, curriculum-aligned practice for the final year of primary school.',
    paragraphs: [
      'Year 6 is a major milestone. As the final year of primary school, it is when students bring together many of the skills they have developed and begin preparing for the more advanced maths they will meet in secondary school.',
      'Students work with more complex number concepts — larger numbers, multiplication, division, fractions, decimals, percentages, ratios, patterns, measurement, geometry, angles, data, chance and multi-step word problems. MyMathsHero helps them practise fraction operations, decimal calculations, percentage problems, area and volume, angles, graph interpretation and real-world maths applications.',
      'Many Year 6 students feel pressure as they prepare for high school. MyMathsHero uses personalised AI-powered learning to identify each child\'s needs and provide questions that match their ability, aligned with curriculum standards across Australian states and territories.',
      'With the right support and consistent practice, Year 6 students can improve accuracy, strengthen problem-solving skills and enter secondary school with greater confidence.',
    ],
    skills: ['Fraction and decimal operations', 'Percentages and ratios', 'Area and volume', 'Angles and geometry', 'Graph interpretation', 'Multi-step real-world problems'],
  },
}

export const YEAR_ORDER = ['prep', 'year-1', 'year-2', 'year-3', 'year-4', 'year-5', 'year-6']
